#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for optimizer/path
#
# IDENTIFICATION
#    src/backend/optimizer/path/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/optimizer/jop
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	jop_extension.o

include $(top_srcdir)/src/backend/common.mk
